import type { CSSProperties } from "react";

/** Shared styles for the agent and skill Context tabs. */
export const s = {
  wrap: {
    padding: "20px 28px 40px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
    maxWidth: 860,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    width: 220,
  } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  row: (attached: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid " + (attached ? "var(--border-strong)" : "var(--border)"),
    background: dragging ? "var(--bg-hover)" : attached ? "var(--bg-elevated)" : "transparent",
    marginBottom: 6,
  }),
  handle: (attached: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    cursor: attached ? "grab" : "default",
    opacity: attached ? 1 : 0.35,
    flexShrink: 0,
  }),
  path: {
    fontSize: 13,
    fontWeight: 600,
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  spacer: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  arrow: (disabled: boolean): CSSProperties => ({
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: 3,
    display: "inline-flex",
    cursor: disabled ? "not-allowed" : "pointer",
    color: disabled ? "var(--text-muted)" : "var(--text-secondary)",
    opacity: disabled ? 0.4 : 1,
  }),
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  tokenCell: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,

  /** The preview control — on every row, attached or not, inherited included. */
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 9px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  previewBody: { padding: "18px 24px" } satisfies CSSProperties,
  previewLoading: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "18px 24px",
  } satisfies CSSProperties,

  /** The read-only inherited group. No checkbox, no handle — read-only means it. */
  inheritedHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  } satisfies CSSProperties,
  inheritedTitle: { fontSize: 14, fontWeight: 650 } satisfies CSSProperties,
  inheritedRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px dashed var(--border)",
    marginBottom: 6,
  } satisfies CSSProperties,

  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    fontSize: 13,
  } satisfies CSSProperties,
  budgetOf: { color: "var(--text-muted)" } satisfies CSSProperties,
  warning: {
    width: "100%",
    fontSize: 13,
    color: "var(--warn)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  perPrompt: {
    width: "100%",
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,

  /** SERIALIZES AS — the block the skill editor shows. */
  serializes: { display: "flex", flexDirection: "column", gap: 6, marginTop: 6 } satisfies CSSProperties,
  serializesPre: {
    margin: 0,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    overflowX: "auto",
  } satisfies CSSProperties,
} as const;
