// GENERATED by scripts/sync-seed-skills.mjs — do not edit by hand.
// The canonical bodies live in docs/skills/*.md; re-run the script after editing
// one. The DB row is the source of truth at run time, so editing here only
// affects freshly seeded workspaces.

/** Mirrors docs/skills/uncovered-branch-rubric.md. */
export const UNCOVERED_BRANCH_RUBRIC = `# Uncovered branch rubric

Work through these steps in order and report what they turn up.

1. List every branch this diff introduces or modifies. A branch is: an \`if\`, an
   \`else\` / \`else if\`, a ternary, a \`switch\` case, a \`catch\`, an early \`return\` or
   \`throw\`, a \`??\` or \`||\` default, an optional chain that can short-circuit, a
   loop body that can run zero times, and each new member of a union or enum.
2. For each branch, name the added or changed test that executes it, quoting that
   test's name.
3. Report every branch for which step 2 found nothing. Cite the changed source
   line that carries the branch — not the test file, and not the file where the
   missing test would live.
4. A branch reachable only through an error path still counts. So does the
   zero-iteration case of a loop and the empty-collection case of a query.
5. For the branches that do have a test, check their boundaries: if a test covers
   \`n > 0\`, is there one for \`n === 0\`? If it covers a non-empty string, is there
   one for \`""\`? Report a missing boundary only when crossing it changes
   behaviour.

A test that drives a branch through a public entry point covers it. Do not report
a branch as uncovered merely because the test reaches it indirectly.`;

/** Mirrors docs/skills/boundary-and-edge-case-rubric.md. */
export const BOUNDARY_AND_EDGE_CASE_RUBRIC = `# Boundary and edge-case rubric

The branch rubric finds the cases the code spells out as an \`if\`. This one finds
the cases it does not: the inputs where behaviour changes without any branch
saying so.

Work through these steps in order.

1. List every value this diff accepts from outside — a parameter, a request
   field, a row read from the database, a number parsed from text. For each, say
   what type it is and where its behaviour changes.
2. For each value, check the boundaries below that apply to it, and name the
   added or changed test that pins each one. Report every boundary with no such
   test.

   - **Numbers.** Zero. Negative. The exact value of any \`min\`/\`max\` bound, and
     one on each side of it. A non-integer where an integer is assumed. \`NaN\` and
     \`Infinity\`, when they can arrive.
   - **Money and rounding.** A value that lands exactly halfway — \`1.005\`, \`2.5\`
     — where binary floating point does not do what decimal arithmetic would.
     Any \`Math.round\` over a scaled amount needs a test at the half.
   - **Strings.** Empty. Whitespace only. Longer than any stated cap. Characters
     outside ASCII, including ones that are two code units.
   - **Collections.** Empty. Exactly one element. The first and the last element,
     when position matters. Duplicates, when uniqueness is assumed.
   - **Absence.** \`null\`, \`undefined\`, and a key that is missing entirely, where
     the three are not the same thing.
   - **Time.** A boundary the code can cross while running: midnight, the end of
     a month or a year, a daylight-saving shift, a timezone that is not the
     machine's.

3. Report a boundary only when crossing it changes behaviour. A cap that nothing
   approaches, or a string the system always generates itself, is not a finding.

Cite the changed source line that introduces the value, not the test file and not
the file where the missing test would live.`;

/** Mirrors docs/skills/assertion-strength-rubric.md. */
export const ASSERTION_STRENGTH_RUBRIC = `# Assertion strength rubric

Coverage tells you a line ran. This asks the harder question: would the test
FAIL if the code were wrong?

For every test this diff adds or changes, work through these steps.

1. State what the test claims, in one sentence, from its name and its
   assertions.
2. Name the smallest change to the production code that would break that claim.
   Pick from what the diff actually contains: a flipped comparison, an off-by-one
   in a bound, two arguments swapped, a dropped \`await\`, a constant changed from
   \`100\` to \`10\`, an early return added, a sign inverted.
3. Decide whether the test would fail on that change. If it would still pass,
   that is the finding: name the change that survives, and say which assertion
   fails to notice it.
4. Check the assertion is about the RESULT, not about the journey. Asserting that
   a function was called, that a value is truthy, or that \`typeof x\` is
   \`'number'\` survives nearly every change worth catching — \`NaN\` is a number.
5. Check the expected value is written down rather than computed. If the test
   derives what it expects the same way the code derives it, the two are wrong
   together and the test cannot tell you so.

Report at most one finding per test, and name the surviving change in it. A test
that would catch every change you can think of is a good test — say nothing about
it.`;

/** Mirrors docs/skills/test-smell-catalogue.md. */
export const TEST_SMELL_CATALOGUE = `# Test smell catalogue

Check every test this diff adds or changes against each item below. Report a match
by citing the test's changed line and naming which item it is.

- **Mocking the unit under test.** The thing being tested is replaced by a fake, so
  the test proves the fake works.
- **Asserting on a mock instead of on behaviour.** \`expect(spy).toHaveBeenCalled()\`
  with nothing checking what the call produced. A test that pins the call graph
  rather than the result breaks on every refactor and lets real bugs through.
- **No assertion at all.** A test whose body cannot fail — no \`expect\`, or only
  \`expect(true).toBe(true)\`.
- **An assertion that restates the implementation.** When the expected value is
  computed the way the code computes it, the test cannot catch a wrong formula.
- **A snapshot standing in for a claim.** A snapshot over a structure this diff
  changed, re-recorded in the same commit, asserts only that the output equals
  itself.
- **Over-broad matching.** \`expect.anything()\`, \`expect.any(Object)\`, or a regex
  loose enough that the wrong value passes.
- **One test, many behaviours.** A test named "works" whose body exercises four
  paths: when it fails you learn nothing about which one.
- **Testing at the wrong level.** A hermetic unit test reaching for a real
  database, network or filesystem; or an integration test asserting something a
  pure-function test would pin faster and more precisely.`;

/** Mirrors docs/skills/breaking-change-taxonomy.md. */
export const BREAKING_CHANGE_TAXONOMY = `# Breaking change taxonomy

Classify every contract change in the diff against this table and report it at the
severity given. Do not reach for a severity outside it.

**CRITICAL — an existing caller breaks, with no version, flag or fallback**

- A response field removed or renamed.
- A request field that was optional becoming required.
- A type narrowed: a union shrunk, a nullable field made non-null, a free string
  constrained to an enum.
- Validation tightened: a new \`min\`, \`max\`, \`regex\`, \`uuid\` or length bound on an
  input that already existed.
- A status code changed for an outcome that already had one.
- A route path or method renamed with no alias left behind.

**WARNING — survivable, but the change is not fully landed**

- A shared contract changed in one copy and not its mirror.
- Documentation still describing the previous shape.
- A default changed so that callers who omit the field now behave differently.
- A field deprecated in prose while still required in the schema.

**SUGGESTION — nothing observable breaks**

- A new optional request or response field.
- Validation loosened, or a union widened.
- A rename confined to code no caller can reach.

For every finding, state the request a caller sends today and what changes about
the reply, then cite the changed line that makes it so.`;

/** Mirrors docs/skills/route-signature-checklist.md. */
export const ROUTE_SIGNATURE_CHECKLIST = `# Route signature checklist

In this repository a route's contract is three things that must move together:

1. the Zod \`schema.params\` / \`schema.body\` declared in \`modules/<name>/routes.ts\`;
2. the DTO mapping in that module's \`helpers.ts\`, which decides every field a
   caller actually receives;
3. the contract under \`vendor/shared/contracts/\`, which exists as TWO byte-identical
   copies — one in \`server/src/vendor/shared\`, one in \`client/src/vendor/shared\`.

For every route the diff touches, check each of these:

- **Did all three move?** A change to one without the others is the break.
- **Was the shared contract mirrored into both copies?** One copy edited is a
  half-landed change that type-checking cannot see, because each package compiles
  against its own copy.
- **Does the route still validate what the handler reads?** A field read from
  \`req.body\` but absent from the schema arrives as \`undefined\` at runtime.
- **Did a response field disappear?** \`client/src/lib/api.ts\` does NOT validate
  responses — it types them with generics only. A removed field therefore fails
  nowhere near the boundary; it surfaces as \`undefined\` deep inside a component,
  at a moment unrelated to this diff. Treat a silently removed response field as
  CRITICAL.
- **Is the workspace scope still applied?** A route that stopped filtering by
  workspace is a tenancy break, not a contract nicety.`;

export interface SeedSkill {
  name: string;
  description: string;
  type: 'rubric' | 'convention' | 'security' | 'custom';
  body: string;
}

/**
 * The skills a fresh workspace starts with, in binding order.
 *
 * "Flakiness patterns" is deliberately absent: it ships as an archive under
 * docs/skills/flakiness-patterns/ and is imported by hand, so the import path is
 * exercised by a person rather than asserted by a fixture.
 */
export const SEED_SKILLS: SeedSkill[] = [
  {
    name: "Uncovered branch rubric",
    description: "List every branch this diff adds and name the test that covers it; report the ones with none.",
    type: "rubric",
    body: UNCOVERED_BRANCH_RUBRIC,
  },
  {
    name: "Boundary and edge-case rubric",
    description: "Check the inputs where behaviour changes without a branch saying so: zero, empty, the exact limit, a rounding half, a timezone.",
    type: "rubric",
    body: BOUNDARY_AND_EDGE_CASE_RUBRIC,
  },
  {
    name: "Assertion strength rubric",
    description: "For each test, name the smallest code change that would still let it pass; report the ones that survive.",
    type: "rubric",
    body: ASSERTION_STRENGTH_RUBRIC,
  },
  {
    name: "Test smell catalogue",
    description: "Flag tests that assert on mocks, restate the implementation, or cannot fail at all.",
    type: "convention",
    body: TEST_SMELL_CATALOGUE,
  },
  {
    name: "Breaking change taxonomy",
    description: "Classify every contract change as breaking or additive, and take its severity from the table.",
    type: "rubric",
    body: BREAKING_CHANGE_TAXONOMY,
  },
  {
    name: "Route signature checklist",
    description: "Check that a route's schema, its DTO mapping and both copies of its shared contract moved together.",
    type: "convention",
    body: ROUTE_SIGNATURE_CHECKLIST,
  },
];
