// GENERATED by scripts/sync-seed-skills.mjs — do not edit by hand.
// The canonical bodies live in docs/skills/*.md; re-run the script after editing
// one. The DB row is the source of truth at run time, so editing here only
// affects freshly seeded workspaces.

/** Mirrors docs/skills/uncovered-branch-rubric.md. */
export const UNCOVERED_BRANCH_RUBRIC = `# Uncovered branch rubric

Work through these steps in order and report what they turn up.

1. List every branch this diff introduces or modifies. A branch is: an \`if\`, an
   \`else\` / \`else if\`, a ternary, a \`switch\` case, a \`catch\`, an early \`return\` or
   \`throw\`, a \`??\` or \`||\` default, an optional chain that can short-circuit, a
   loop body that can run zero times, and each new member of a union or enum.
2. For each branch, name the added or changed test that executes it, quoting that
   test's name.
3. Report every branch for which step 2 found nothing. Cite the changed source
   line that carries the branch — not the test file, and not the file where the
   missing test would live.
4. A branch reachable only through an error path still counts. So does the
   zero-iteration case of a loop and the empty-collection case of a query.
5. For the branches that do have a test, check their boundaries: if a test covers
   \`n > 0\`, is there one for \`n === 0\`? If it covers a non-empty string, is there
   one for \`""\`? Report a missing boundary only when crossing it changes
   behaviour.

A test that drives a branch through a public entry point covers it. Do not report
a branch as uncovered merely because the test reaches it indirectly.`;

/** Mirrors docs/skills/test-smell-catalogue.md. */
export const TEST_SMELL_CATALOGUE = `# Test smell catalogue

Check every test this diff adds or changes against each item below. Report a match
by citing the test's changed line and naming which item it is.

- **Mocking the unit under test.** The thing being tested is replaced by a fake, so
  the test proves the fake works.
- **Asserting on a mock instead of on behaviour.** \`expect(spy).toHaveBeenCalled()\`
  with nothing checking what the call produced. A test that pins the call graph
  rather than the result breaks on every refactor and lets real bugs through.
- **No assertion at all.** A test whose body cannot fail — no \`expect\`, or only
  \`expect(true).toBe(true)\`.
- **An assertion that restates the implementation.** When the expected value is
  computed the way the code computes it, the test cannot catch a wrong formula.
- **A snapshot standing in for a claim.** A snapshot over a structure this diff
  changed, re-recorded in the same commit, asserts only that the output equals
  itself.
- **Over-broad matching.** \`expect.anything()\`, \`expect.any(Object)\`, or a regex
  loose enough that the wrong value passes.
- **One test, many behaviours.** A test named "works" whose body exercises four
  paths: when it fails you learn nothing about which one.
- **Testing at the wrong level.** A hermetic unit test reaching for a real
  database, network or filesystem; or an integration test asserting something a
  pure-function test would pin faster and more precisely.`;

/** Mirrors docs/skills/breaking-change-taxonomy.md. */
export const BREAKING_CHANGE_TAXONOMY = `# Breaking change taxonomy

Classify every contract change in the diff against this table and report it at the
severity given. Do not reach for a severity outside it.

**CRITICAL — an existing caller breaks, with no version, flag or fallback**

- A response field removed or renamed.
- A request field that was optional becoming required.
- A type narrowed: a union shrunk, a nullable field made non-null, a free string
  constrained to an enum.
- Validation tightened: a new \`min\`, \`max\`, \`regex\`, \`uuid\` or length bound on an
  input that already existed.
- A status code changed for an outcome that already had one.
- A route path or method renamed with no alias left behind.

**WARNING — survivable, but the change is not fully landed**

- A shared contract changed in one copy and not its mirror.
- Documentation still describing the previous shape.
- A default changed so that callers who omit the field now behave differently.
- A field deprecated in prose while still required in the schema.

**SUGGESTION — nothing observable breaks**

- A new optional request or response field.
- Validation loosened, or a union widened.
- A rename confined to code no caller can reach.

For every finding, state the request a caller sends today and what changes about
the reply, then cite the changed line that makes it so.`;

/** Mirrors docs/skills/route-signature-checklist.md. */
export const ROUTE_SIGNATURE_CHECKLIST = `# Route signature checklist

In this repository a route's contract is three things that must move together:

1. the Zod \`schema.params\` / \`schema.body\` declared in \`modules/<name>/routes.ts\`;
2. the DTO mapping in that module's \`helpers.ts\`, which decides every field a
   caller actually receives;
3. the contract under \`vendor/shared/contracts/\`, which exists as TWO byte-identical
   copies — one in \`server/src/vendor/shared\`, one in \`client/src/vendor/shared\`.

For every route the diff touches, check each of these:

- **Did all three move?** A change to one without the others is the break.
- **Was the shared contract mirrored into both copies?** One copy edited is a
  half-landed change that type-checking cannot see, because each package compiles
  against its own copy.
- **Does the route still validate what the handler reads?** A field read from
  \`req.body\` but absent from the schema arrives as \`undefined\` at runtime.
- **Did a response field disappear?** \`client/src/lib/api.ts\` does NOT validate
  responses — it types them with generics only. A removed field therefore fails
  nowhere near the boundary; it surfaces as \`undefined\` deep inside a component,
  at a moment unrelated to this diff. Treat a silently removed response field as
  CRITICAL.
- **Is the workspace scope still applied?** A route that stopped filtering by
  workspace is a tenancy break, not a contract nicety.`;

export interface SeedSkill {
  name: string;
  description: string;
  type: 'rubric' | 'convention' | 'security' | 'custom';
  body: string;
}

/**
 * The skills a fresh workspace starts with, in binding order.
 *
 * "Flakiness patterns" is deliberately absent: it ships as an archive under
 * docs/skills/flakiness-patterns/ and is imported by hand, so the import path is
 * exercised by a person rather than asserted by a fixture.
 */
export const SEED_SKILLS: SeedSkill[] = [
  {
    name: "Uncovered branch rubric",
    description: "List every branch this diff adds and name the test that covers it; report the ones with none.",
    type: "rubric",
    body: UNCOVERED_BRANCH_RUBRIC,
  },
  {
    name: "Test smell catalogue",
    description: "Flag tests that assert on mocks, restate the implementation, or cannot fail at all.",
    type: "convention",
    body: TEST_SMELL_CATALOGUE,
  },
  {
    name: "Breaking change taxonomy",
    description: "Classify every contract change as breaking or additive, and take its severity from the table.",
    type: "rubric",
    body: BREAKING_CHANGE_TAXONOMY,
  },
  {
    name: "Route signature checklist",
    description: "Check that a route's schema, its DTO mapping and both copies of its shared contract moved together.",
    type: "convention",
    body: ROUTE_SIGNATURE_CHECKLIST,
  },
];
