import type { CSSProperties } from "react";

/** Co-located styles for the import drawer. */
export const s = {
  body: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  drop: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
    padding: "36px 24px",
    borderRadius: 10,
    border: "1px dashed var(--border-strong)",
    background: "var(--bg-elevated)",
    textAlign: "center",
  } satisfies CSSProperties,
  dropIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  dropHint: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5, maxWidth: 420 } satisfies CSSProperties,
  urlPane: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  urlActions: { display: "flex", justifyContent: "flex-end" } satisfies CSSProperties,
  trust: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
  } satisfies CSSProperties,
  trustTitle: { fontSize: 13, fontWeight: 700 } satisfies CSSProperties,
  trustBody: { fontSize: 13, lineHeight: 1.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  meta: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", fontSize: 12 } satisfies CSSProperties,
  metaLabel: { color: "var(--text-muted)" } satisfies CSSProperties,
  chip: {
    fontSize: 12,
    padding: "1px 8px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  evidence: { marginLeft: "auto", color: "var(--text-muted)" } satisfies CSSProperties,
  skipped: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  skippedTitle: { fontSize: 12, fontWeight: 700, color: "var(--text-secondary)" } satisfies CSSProperties,
  skippedList: { display: "flex", flexDirection: "column", gap: 4, listStyle: "none" } satisfies CSSProperties,
  skippedRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 12 } satisfies CSSProperties,
  skippedPath: { color: "var(--text-secondary)" } satisfies CSSProperties,
  skippedReason: { marginLeft: "auto", color: "var(--text-muted)" } satisfies CSSProperties,
  warning: { fontSize: 12, color: "var(--warn)" } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "flex-end", gap: 10 } satisfies CSSProperties,
} as const;
