import type { CSSProperties } from "react";

/** Co-located styles for the wizard's Preview step. */
export const s = {
  pane: {
    display: "grid",
    gridTemplateColumns: "260px minmax(0, 1fr)",
    height: 340,
    border: "1px solid var(--border)",
    borderRadius: 9,
    overflow: "hidden",
  } satisfies CSSProperties,
  list: {
    borderRight: "1px solid var(--border)",
    padding: 10,
    background: "var(--bg-surface)",
    overflow: "auto",
  } satisfies CSSProperties,
  listLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-muted)",
    letterSpacing: "0.05em",
    padding: "2px 8px 8px",
  } satisfies CSSProperties,
  row: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 7,
    width: "100%",
    padding: "5px 8px",
    borderRadius: 5,
    border: "none",
    cursor: "pointer",
    fontSize: 12,
    textAlign: "left",
    fontFamily: "inherit",
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
  }),
  rowIcon: (active: boolean): CSSProperties => ({
    color: active ? "var(--accent)" : "var(--text-muted)",
    flexShrink: 0,
  }),
  rowPath: { overflowWrap: "anywhere" } satisfies CSSProperties,
  editor: { display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  editorHead: {
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  editorPath: { fontSize: 12, flex: 1, overflowWrap: "anywhere" } satisfies CSSProperties,
  code: {
    margin: 0,
    padding: 14,
    fontSize: 11.5,
    lineHeight: 1.6,
    overflow: "auto",
    flex: 1,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  textarea: {
    margin: 0,
    padding: 14,
    fontSize: 11.5,
    lineHeight: 1.6,
    flex: 1,
    width: "100%",
    resize: "none",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
    background: "var(--code-bg)",
  } satisfies CSSProperties,
  placeholder: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 24,
    textAlign: "center",
    background: "var(--code-bg)",
  } satisfies CSSProperties,
  placeholderSize: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  placeholderBody: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  state: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 340,
    border: "1px solid var(--border)",
    borderRadius: 9,
    fontSize: 13,
    color: "var(--text-muted)",
    padding: 24,
    textAlign: "center",
  } satisfies CSSProperties,
} as const;
