import type {
  CiExport,
  CiExportInput,
  CiFile,
  CiInstallation,
  CiInstallationListItem,
  CiRun,
} from '@devdigest/shared';
import type { PinoLike } from '../../platform/run-logger.js';
import { ValidationError } from '../../platform/errors.js';
import {
  CI_INGEST_JOB_KIND,
  COMMIT_MESSAGE,
  PR_TITLE,
  PUBLISH_BRANCH,
  workflowPathFor,
} from './constants.js';
import { attachedSkills } from '../_shared/attached-skills.js';
import { buildBundle } from './generate/bundle.js';
import { findYamlProblem } from './generate/yaml-lint.js';
import { agentSlug as agentSlugFor } from './generate/slug.js';
import {
  parseRepoRef,
  toCiInstallation,
  toCiRun,
  toInstallationListItem,
  zipFiles,
} from './helpers.js';
import { CiIngestExecutor } from './ingest-executor.js';
import { CiRepository } from './repository.js';
import type {
  CiContainer,
  CiRefreshPage,
  CiRunsPage,
  GeneratedBundle,
  IngestOutcome,
  PollError,
} from './types.js';

/**
 * Export to CI — the use cases behind the five routes.
 *
 * Two halves that share a repository and nothing else. GENERATE AND INSTALL
 * turns an agent row into the `CiFile[]` of AC-16 and, on request, commits it to
 * a target repository through the GitHub port. READ AND REFRESH answers the CI
 * Runs page and drives the pull-based ingest.
 *
 * Neither half ever reads a secret itself: `container.github()` resolves the
 * token through `SecretsProvider`, and the generator is not given the provider
 * at all — which is what makes AC-25 ("no generated file carries a secret's
 * value") a property of the code's SHAPE rather than of a test.
 */

export type { CiRefreshPage, CiRunsPage } from './types.js';

const NO_INGEST: IngestOutcome = { errors: [], polled: 0, accepted: 0, rejected: 0 };

/**
 * The PR body (AC-37, AC-38, AC-45).
 *
 * The count comes from the generated list's length, never a constant: the list
 * is one file per bound skill plus five, so an agent that gains a skill and a
 * text that says "6 files" disagree the moment they are read together.
 *
 * `OPENROUTER_API_KEY` is named, never valued — DevDigest does not read the
 * target repository's key and cannot fill it in (AC-92).
 */
function prBody(repo: string, fileCount: number): string {
  return [
    `DevDigest adds an automated pull-request review to \`${repo}\`.`,
    '',
    `This branch carries ${fileCount} generated files: the agent manifest, one file per bound ` +
      'skill, an empty memory file, the runner bundle and the workflow that runs it.',
    '',
    'ONE STEP IS LEFT TO YOU. Add `OPENROUTER_API_KEY` under Settings → Secrets and variables →',
    'Actions of this repository. Until it is there the review job has no model to call.',
    '',
    'Generated by DevDigest — edit the agent in the studio and re-export.',
  ].join('\n');
}

export class CiService {
  /**
   * What each ingest job returned, keyed by its job id.
   *
   * `JobHandler` resolves to `void`, and the refresh route has to answer with
   * `errors[]` (AC-83) — so the outcome is handed back through this map rather
   * than through the runner. Written by the handler, read and deleted by the
   * one caller that awaited that exact job, so it holds at most one entry per
   * in-flight refresh.
   */
  private readonly ingests = new Map<string, IngestOutcome>();

  constructor(
    private container: CiContainer,
    private repo: CiRepository = new CiRepository(container.db),
  ) {}

  /**
   * Register the ingest handler once, at module registration.
   *
   * The runner stores the closure rather than this instance, so registering
   * from the route plugin and reaching the service through it are the same
   * thing — the shape `context/service.ts:79` already uses. The timeout, the
   * retries and the concurrency are the shared `JobRunner`'s, which is what the
   * spec's non-functional table names for this job.
   */
  registerIngestJobHandler(log: PinoLike): void {
    const executor = new CiIngestExecutor(this.container, this.repo, log);
    this.container.jobs.register(CI_INGEST_JOB_KIND, async (payload, { jobId }) => {
      const { workspaceId, force } = payload as { workspaceId: string; force: boolean };
      this.ingests.set(jobId, await executor.run({ workspaceId, force }));
    });
  }

  // -------------------------------------------------------------------------
  // Generate and install
  // -------------------------------------------------------------------------

  /** One agent's installations, each with its last run and its staleness (AC-85, AC-90). */
  async installations(
    workspaceId: string,
    agentId: string,
  ): Promise<CiInstallationListItem[] | undefined> {
    const agent = await this.container.agentsRepo.getById(workspaceId, agentId);
    if (!agent) return undefined;
    const rows = await this.repo.listForAgent(workspaceId, agentId);
    return rows.map(toInstallationListItem);
  }

  /**
   * `POST /agents/:id/export-ci` — generate, and for `open_pr` publish.
   *
   * ORDER IS THE REQUIREMENT. The commit and the PR happen first and the
   * installation row last, so a GitHub refusal — no permission, repo not found,
   * invalid token — propagates with no row written (AC-43). Reversing the two
   * would leave DevDigest polling a repository it never reached.
   */
  async export(
    workspaceId: string,
    agentId: string,
    input: CiExportInput,
  ): Promise<CiExport | undefined> {
    const built = await this.build(workspaceId, agentId, input);
    if (!built) return undefined;
    const { files, agentVersion, agentSlug, removals } = built;

    if (input.action !== 'open_pr') {
      return {
        installation: await this.installationPreview(agentId, input.repo, agentVersion),
        files,
        removals,
        pr_url: null,
      };
    }

    await this.refuseSlugCollision(workspaceId, agentId, input.repo, agentSlug);

    const ref = parseRepoRef(input.repo);
    const gh = await this.container.github();
    await gh.commitFiles(ref, {
      // Never the base branch (AC-40) — `commitFiles` forks `base` when
      // `devdigest/ci` does not exist yet and fast-forwards it when it does.
      branch: PUBLISH_BRANCH,
      base: input.base,
      message: COMMIT_MESSAGE,
      files: files.map((f) => ({ path: f.path, contents: f.contents })),
      // ONE COMMIT for the new files and the legacy one (AC-146), so the branch
      // is never observable with two workflows for this agent or with none.
      deletions: removals,
    });
    // AFTER the commit, so a re-publish adds to the branch the open PR already
    // tracks and returns that PR rather than opening a second one (AC-41).
    const existing = await gh.findOpenPr(ref, PUBLISH_BRANCH);
    const pr =
      existing ??
      (await gh.openPullRequest(ref, {
        title: PR_TITLE,
        head: PUBLISH_BRANCH,
        base: input.base,
        body: prBody(input.repo, files.length),
      }));

    const row = await this.repo.upsertInstallation({
      agentId,
      repo: input.repo,
      targetType: 'gha',
      agentVersion,
    });
    return { installation: toCiInstallation(row), files, removals, pr_url: pr.url };
  }

  /**
   * `POST /agents/:id/export-ci/zip` — the same files, as an archive (AC-44).
   *
   * No GitHub call and no installation row, which is also why the Install step
   * says plainly that DevDigest will never see this repository's runs (AC-119):
   * without a row the ingest has nothing to poll.
   *
   * It takes the SAME body as the PR route, `workflow` included, so it gets the
   * AC-55 refusal from `build` for the same reason the PR route does: an
   * unparseable workflow zipped up is committed by hand a minute later.
   */
  async zip(
    workspaceId: string,
    agentId: string,
    input: CiExportInput,
  ): Promise<Uint8Array | undefined> {
    const built = await this.build(workspaceId, agentId, input);
    return built ? zipFiles(built.files) : undefined;
  }

  /**
   * The agent's row + its skills + the built runner → the ordered `CiFile[]` of
   * AC-16, and the one place the AC-55 refusal is applied.
   *
   * IN HERE, and not in `export`, because every route that produces files goes
   * through this method: the PR path used to be the only one that refused, so
   * "Copy files as a zip" would have packaged an unparseable workflow the moment
   * the wizard learnt to send one. A gate a caller has to remember is a gate one
   * caller will not.
   */
  private async build(
    workspaceId: string,
    agentId: string,
    input: CiExportInput,
  ): Promise<(GeneratedBundle & { agentVersion: number }) | undefined> {
    const agent = await this.container.agentsRepo.getById(workspaceId, agentId);
    if (!agent) return undefined;
    const linked = await this.container.agentsRepo.linkedSkills(agentId);
    const runner = await this.container.runnerBundle.read();

    const { files, agentSlug, removals } = buildBundle({
      agent: {
        id: agent.id,
        name: agent.name,
        model: agent.model,
        systemPrompt: agent.systemPrompt,
        strategy: agent.strategy,
        // The agent's CURRENT policy, including `any` — the manifest is what the
        // runner gates on, and the three-way control on the CI tab is a
        // narrower vocabulary than the column's (AC-26).
        ciFailOn: agent.ciFailOn,
      },
      // The same two filters the studio applies before a body becomes an
      // instruction (`_shared/attached-skills.ts`). Without them a globally
      // disabled skill, and a body the injection detector flagged, were
      // published into someone else's repository and executed by the runner
      // while this agent ignored them here.
      skills: attachedSkills(linked).map((l) => ({
        id: l.skill.id,
        name: l.skill.name,
        body: l.skill.body,
      })),
      runner,
      triggers: input.triggers,
      postAs: input.post_as,
      workflowOverride: input.workflow,
    });
    this.refuseBrokenWorkflow(files);
    return { files, agentVersion: agent.version, agentSlug, removals };
  }

  /**
   * Refuse to publish a bundle whose file name another agent already owns here
   * (AC-137).
   *
   * TWO AGENTS, ONE SLUG. "Security Reviewer" and "security reviewer" both
   * resolve to `security-reviewer` (AC-17), so per-agent paths do not by
   * themselves make two agents safe to publish into one repository — they only
   * move the collision from every pair of agents to the pairs that slug alike.
   * Refusing is the whole point: the alternative is the defect this change
   * exists to remove, one repository further in.
   *
   * The publishing agent is excluded by ID, not by slug: republishing an agent
   * into a repository it already occupies is AC-41, and must keep working.
   */
  private async refuseSlugCollision(
    workspaceId: string,
    agentId: string,
    repo: string,
    agentSlug: string,
  ): Promise<void> {
    const installed = await this.repo.listInstallationsInRepo(workspaceId, repo);
    const clash = installed.find(
      (i) => i.agentId !== agentId && agentSlugFor({ id: i.agentId, name: i.agentName }) === agentSlug,
    );
    if (!clash) return;
    throw new ValidationError(
      `"${clash.agentName}" is already installed in ${repo} and resolves to the same ` +
        `file name — both agents would write ${workflowPathFor(agentSlug)}. ` +
        'Rename one of the agents, then install again.',
    );
  }

  /**
   * Refuse a workflow that is not YAML, naming the line, before anything is
   * committed (AC-55).
   *
   * REFUSE, NEVER REPAIR. The text is about to be written into someone else's
   * repository and then executed by GitHub; `server/INSIGHTS.md` — "A length cap
   * applied to a string that will be EXECUTED has to reject it" — is the same
   * principle one layer up. A generated workflow always passes, so this is only
   * ever reached by a hand edit; running it on both is what keeps a change to
   * the generator from quietly shipping a broken file.
   *
   * Called from `build`, so the PR, the zip and the generate-only preview all
   * get it. See `build`.
   */
  private refuseBrokenWorkflow(files: CiFile[]): void {
    // BY ROLE, not by path: the path carries the agent's slug now (AC-135), and
    // a `find` against a constant would have silently stopped matching — the
    // refusal would never fire and a hand-edited, unparseable workflow would be
    // committed. The message still names the real path, which is the half of
    // AC-55 a role cannot supply.
    const workflow = files.find((f) => f.role === 'workflow');
    if (!workflow) return;
    const problem = findYamlProblem(workflow.contents);
    if (problem) {
      throw new ValidationError(
        `${workflow.path} is not valid YAML — line ${problem.line}: ${problem.message}`,
      );
    }
  }

  /**
   * The `installation` a generate-only export answers with.
   *
   * `CiExport.installation` is not nullable and `action: 'files'` writes no row
   * (AC-7, AC-44), so this returns the EXISTING row when the agent is already
   * installed in that repository — which is also what tells the wizard to call
   * the repository out before Install (AC-104) — and an un-persisted
   * description of the row Install would create when it is not. The empty `id`
   * is what says nothing was written.
   */
  private async installationPreview(
    agentId: string,
    repo: string,
    agentVersion: number,
  ): Promise<CiInstallation> {
    const existing = await this.repo.findInstallation(agentId, repo);
    if (existing) return toCiInstallation(existing);
    return {
      id: '',
      agent_id: agentId,
      repo,
      target_type: 'gha',
      installed_at: new Date().toISOString(),
      agent_version: agentVersion,
    };
  }

  // -------------------------------------------------------------------------
  // Read and refresh
  // -------------------------------------------------------------------------

  /** `GET /ci/runs` — stored rows, newest first, and the last successful poll. */
  async runs(workspaceId: string): Promise<CiRunsPage> {
    const [rows, polledAt] = await Promise.all([
      this.repo.listRuns(workspaceId),
      this.repo.lastPolledAt(workspaceId),
    ]);
    return { runs: rows.map(toCiRun), last_polled_at: polledAt?.toISOString() ?? null };
  }

  /**
   * `POST /ci/runs/refresh` — poll, then answer with the stored rows (AC-68, AC-120).
   *
   * The rows are read back AFTER the ingest and are never emptied by it: a
   * repository whose poll failed contributes an entry to `errors[]` and leaves
   * what was already ingested on screen (AC-83).
   */
  async refresh(workspaceId: string, force: boolean): Promise<CiRefreshPage> {
    const { errors } = await this.ingest(workspaceId, force);
    return { ...(await this.runs(workspaceId)), errors };
  }

  private async ingest(workspaceId: string, force: boolean): Promise<IngestOutcome> {
    const job = await this.container.jobs.enqueue(workspaceId, CI_INGEST_JOB_KIND, {
      workspaceId,
      force,
    });
    try {
      await job.done;
      return this.ingests.get(job.id) ?? NO_INGEST;
    } finally {
      this.ingests.delete(job.id);
    }
  }
}
