import { AgentManifest, type CiFailOn, type Provider, type ReviewStrategy } from '@devdigest/shared';

/**
 * `.devdigest/agents/<slug>.yaml` — the agent contract the runner reads.
 *
 * Built from the agent's CURRENT row and validated against `AgentManifest`
 * before it is serialised (AC-26), so a manifest that the runner would reject
 * never reaches a commit. Nothing here touches `SecretsProvider`: the manifest
 * carries no key, and the only way to keep AC-25 true is for the generator not
 * to have the values at all.
 */

export interface ManifestInput {
  name: string;
  provider: Provider;
  model: string;
  systemPrompt: string;
  strategy: ReviewStrategy;
  /** The agent's stored gate policy, including `any` (AC-26). */
  ciFailOn: CiFailOn;
  /** Final slugs, resolving to `.devdigest/skills/<slug>.md`. */
  skillSlugs: string[];
}

export function buildManifest(input: ManifestInput): AgentManifest {
  return AgentManifest.parse({
    name: input.name,
    provider: input.provider,
    model: input.model,
    system_prompt: input.systemPrompt,
    skills: input.skillSlugs,
    strategy: input.strategy,
    ci_fail_on: input.ciFailOn,
  });
}

/** Words YAML reads as something other than a string when left unquoted. */
const RESERVED = new Set(['true', 'false', 'null', 'yes', 'no', 'on', 'off', '~']);
/** A plain scalar needs no quoting only if it is this dull. */
const PLAIN = /^[A-Za-z0-9][A-Za-z0-9 ._/@+-]*$/;

function yamlScalar(value: string): string {
  if (value === '') return "''";
  const plain =
    PLAIN.test(value) &&
    !value.endsWith(' ') &&
    !RESERVED.has(value.toLowerCase()) &&
    !/^[-+]?\d+(\.\d+)?$/.test(value);
  return plain ? value : `'${value.replace(/'/g, "''")}'`;
}

/**
 * A literal block scalar with an EXPLICIT indentation indicator (`|2-`).
 *
 * Without the indicator YAML infers the content indentation from the first
 * non-empty line, so a system prompt whose first line is itself indented would
 * shift the whole block and silently re-indent every other line. The indicator
 * says "content starts two columns in" and makes the rest content, whatever it
 * looks like.
 */
function yamlBlock(value: string, key: string): string {
  const lines = value.replace(/\r\n?/g, '\n').split('\n');
  const body = lines.map((line) => (line === '' ? '' : `  ${line}`)).join('\n');
  return `${key}: |2-\n${body}`;
}

/** One `key: value` line, or a block scalar when the value spans lines. */
function yamlField(key: string, value: string): string {
  return value.includes('\n') ? yamlBlock(value, key) : `${key}: ${yamlScalar(value)}`;
}

/** Serialise a validated manifest. Field order is fixed so a re-export diffs cleanly. */
export function manifestToYaml(manifest: AgentManifest): string {
  const skills =
    manifest.skills.length === 0
      ? 'skills: []'
      : ['skills:', ...manifest.skills.map((s) => `  - ${yamlScalar(s)}`)].join('\n');

  return [
    '# Generated by DevDigest. Edit the agent in the studio and re-export.',
    yamlField('name', manifest.name),
    yamlField('provider', manifest.provider),
    yamlField('model', manifest.model),
    yamlField('system_prompt', manifest.system_prompt),
    skills,
    yamlField('strategy', manifest.strategy),
    yamlField('ci_fail_on', manifest.ci_fail_on),
    '',
  ].join('\n');
}
