import { CI_ENV } from '@devdigest/shared';
import {
  ARTIFACT_FILE,
  ARTIFACT_NAME,
  JOB_TIMEOUT_MINUTES,
  MAX_DIFF_LINES,
  PINNED_ACTIONS,
  RUNNER_NODE_VERSION,
  RUNNER_PATH,
  WORKFLOW_PREFIX,
} from '../constants.js';

/**
 * `.github/workflows/devdigest-review-<slug>.yml` (AC-135).
 *
 * The security properties are structural, and each one is a criterion:
 *
 * - `pull_request`, never `pull_request_target` (AC-46) — the latter runs with
 *   the base repository's secrets against the PR's code.
 * - `permissions` is the minimum the chosen publication needs, and nothing else
 *   (AC-33, AC-34).
 * - No `run:` line interpolates `${{ … }}`; everything the runner needs arrives
 *   through `env:` and is read as an environment variable (AC-50). The runner
 *   takes no arguments at all.
 * - `OPENROUTER_API_KEY` appears exactly once, as `${{ secrets.… }}` in the
 *   runner step's `env:` (AC-47).
 * - No `npm install`, `npm ci`, `npx` or `pnpm` anywhere: the bundle is one
 *   self-contained file and the job installs nothing from the network (AC-48).
 * - Every external action is pinned to a 40-character commit SHA with the
 *   version in a comment (AC-49).
 *
 * The fork case is NOT a step that skips the runner. `DEVDIGEST_IS_FORK` reaches
 * the runner, which exits 0 without a model call (AC-52) after writing the job
 * summary (AC-109) and the `skipped` artifact (AC-110) — a workflow-level `if:`
 * would skip the step that writes that artifact, and AC-110 requires it by the
 * same path as the size skip.
 */

export type PostAs = 'github_review' | 'pr_comment' | 'none';

export interface WorkflowInput {
  /** `pull_request` activity types, in the order the wizard offered them. */
  triggers: string[];
  postAs: PostAs;
  /** Manifest slug — `.devdigest/agents/<slug>.yaml`. */
  agentSlug: string;
  /** The agent's name as the studio shows it — the check is named after it (AC-138). */
  agentName: string;
}

/**
 * A YAML double-quoted scalar, whatever the string holds.
 *
 * The agent's name is typed by a workspace user and lands in a file GitHub then
 * EXECUTES, so it is quoted rather than trusted: a name containing `:`, `#`, a
 * quote or a newline would otherwise end the scalar and add keys to the
 * workflow. `JSON.stringify` produces exactly the escapes a YAML double-quoted
 * scalar accepts — `\"`, `\\` and `\uXXXX` for the control characters — which
 * makes this the one place a free string may enter the generated file.
 */
function yamlString(value: string): string {
  return JSON.stringify(value);
}

/**
 * What GitHub calls the check, and why it carries the agent (AC-138).
 *
 * Two agents in one repository must produce two check names, or a branch rule
 * cannot require one agent's review without requiring the other's. The value is
 * used for BOTH the workflow's `name:` and the job's, because the name a branch
 * protection rule matches on is the job's — a workflow name alone would leave
 * both agents' checks called "review" and AC-138 unobservable.
 */
function checkName(agentName: string): string {
  return `DevDigest Review (${agentName})`;
}

function permissionsBlock(postAs: PostAs): string[] {
  // `none` publishes nothing, so write access to pull requests would be a
  // permission the job has and never uses.
  return postAs === 'none'
    ? ['permissions:', '  contents: read']
    : ['permissions:', '  contents: read', '  pull-requests: write'];
}

function pinned(action: (typeof PINNED_ACTIONS)[keyof typeof PINNED_ACTIONS]): string {
  return `${action.name}@${action.sha} # ${action.version}`;
}

export function renderWorkflow(input: WorkflowInput): string {
  const types = input.triggers.join(', ');
  return [
    '# Generated by DevDigest. Regenerate from the agent\'s CI tab after changing',
    '# triggers or "Post results as"; hand edits are kept until you do.',
    `name: ${yamlString(checkName(input.agentName))}`,
    '',
    'on:',
    '  pull_request:',
    `    types: [${types}]`,
    '',
    ...permissionsBlock(input.postAs),
    '',
    'concurrency:',
    // THE SLUG IS IN THE GROUP, and that is AC-139: grouped by PR number alone,
    // the second agent's run on a pull request shares a group with the first's
    // and `cancel-in-progress: true` kills a review that was already running.
    `  group: ${WORKFLOW_PREFIX}${input.agentSlug}-\${{ github.event.pull_request.number }}`,
    '  cancel-in-progress: true',
    '',
    'jobs:',
    '  review:',
    `    name: ${yamlString(checkName(input.agentName))}`,
    '    runs-on: ubuntu-latest',
    `    timeout-minutes: ${JOB_TIMEOUT_MINUTES}`,
    '    steps:',
    `      - uses: ${pinned(PINNED_ACTIONS.checkout)}`,
    `      - uses: ${pinned(PINNED_ACTIONS.setupNode)}`,
    '        with:',
    `          node-version: '${RUNNER_NODE_VERSION}'`,
    '      - name: Run DevDigest review',
    `        run: node ${RUNNER_PATH}`,
    '        env:',
    `          ${CI_ENV.agent}: ${input.agentSlug}`,
    `          ${CI_ENV.repository}: \${{ github.repository }}`,
    `          ${CI_ENV.prNumber}: \${{ github.event.pull_request.number }}`,
    // Cross-repository, NOT `head.repo.fork`. That flag describes where the
    // head repository CAME FROM, not the relationship between head and base,
    // and the two disagree in a repository that is itself a fork: every
    // internal PR there reports `fork: true`. Measured on 2026-08-26 against
    // `Holubinka/dev-digest` (a fork of `ai-agentic-engineering-neo/dev-digest`):
    // a PR from its own `devdigest/ci` branch skipped in 3 ms, called no model
    // and left a green check. Comparing the full names asks the question the
    // secrets rule actually turns on — is the head somewhere else?
    `          ${CI_ENV.isFork}: \${{ github.event.pull_request.head.repo.full_name != github.repository }}`,
    `          ${CI_ENV.postAs}: ${input.postAs}`,
    `          ${CI_ENV.maxDiffLines}: '${MAX_DIFF_LINES}'`,
    `          ${CI_ENV.openRouterKey}: \${{ secrets.${CI_ENV.openRouterKey} }}`,
    `          ${CI_ENV.githubToken}: \${{ secrets.${CI_ENV.githubToken} }}`,
    '      - name: Upload the review result',
    '        if: always()',
    `        uses: ${pinned(PINNED_ACTIONS.uploadArtifact)}`,
    '        with:',
    `          name: ${ARTIFACT_NAME}`,
    `          path: ${ARTIFACT_FILE}`,
    '',
  ].join('\n');
}
